"""Stations Migrations  migration

Revision ID: 21e4ab0b3782
Revises: bf29de487879
Create Date: 2025-05-27 17:48:15.251117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e4ab0b3782'
down_revision: Union[str, None] = 'bf29de487879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('access_link', sa.String(length=500), nullable=True),
    sa.Column('streaming_link', sa.String(length=500), nullable=True),
    sa.Column('listeners', sa.Integer(), nullable=True),
    sa.Column('streaming_status', sa.String(length=50), nullable=True),
    sa.Column('radio_access_status', sa.Boolean(), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_path', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frequency')
    )
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_index(op.f('ix_stations_slug'), 'stations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_slug'), table_name='stations')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
