"""Slugs Stations Migrations  migration

Revision ID: 339ffc6149a8
Revises: 73e06740602c
Create Date: 2025-06-13 05:43:13.613302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339ffc6149a8'
down_revision: Union[str, None] = '73e06740602c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forums', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forums', type_='unique')
    # ### end Alembic commands ###
