"""Systemlogs  Migrations

Revision ID: 406b8bc0bc20
Revises: 5591afa0cbb1
Create Date: 2025-06-22 12:06:39.274511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406b8bc0bc20'
down_revision: Union[str, None] = '5591afa0cbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_session_recordings',
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('recording_status', sa.String(length=20), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('recording_file_path', sa.String(length=500), nullable=True),
    sa.Column('recording_file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('audio_format', sa.String(length=10), nullable=False),
    sa.Column('audio_quality', sa.String(length=20), nullable=False),
    sa.Column('recording_process_id', sa.String(length=100), nullable=True),
    sa.Column('studio', sa.String(length=1), nullable=True),
    sa.Column('hosts', sa.JSON(), nullable=True),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.Column('is_live_session', sa.Boolean(), nullable=True),
    sa.Column('is_repeat_session', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('recording_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['radio_programs.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio_session_recordings')
    # ### end Alembic commands ###
