"""Slugs Stations Migrations  migration

Revision ID: 44973ec12998
Revises: 83abb2f4c446
Create Date: 2025-06-13 06:37:30.331722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44973ec12998'
down_revision: Union[str, None] = '83abb2f4c446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_comments', sa.Column('reply_to', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'forum_comments', 'forum_comments', ['reply_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_comments', type_='foreignkey')
    op.drop_column('forum_comments', 'reply_to')
    # ### end Alembic commands ###
