"""Stations Migrations  migration

Revision ID: 7aff513e96b5
Revises: dd8073076520
Create Date: 2025-06-13 05:36:20.269562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7aff513e96b5'
down_revision: Union[str, None] = 'dd8073076520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forums', sa.Column('slug', sa.String(length=500), nullable=False, unique=True, index=True, default=func.lower(func.concat('forum_', func.md5(func.concat('forum_', func.now()))))))
    op.add_column('forums', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('forums', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.alter_column('news', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.drop_column('forums', 'is_published')
    op.drop_column('forums', 'is_pinned')
    op.drop_column('forums', 'slug')
    # ### end Alembic commands ###
