"""Systemlogs  Migrations

Revision ID: 7d4d885ab161
Revises: 0e4f0742ef19
Create Date: 2025-06-18 08:29:44.032683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4d885ab161'
down_revision: Union[str, None] = '0e4f0742ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_listeners', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_listeners', 'last_seen')
    # ### end Alembic commands ###
