"""Slugs Stations Migrations  migration

Revision ID: 83abb2f4c446
Revises: 339ffc6149a8
Create Date: 2025-06-13 05:59:52.851114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83abb2f4c446'
down_revision: Union[str, None] = '339ffc6149a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forums', sa.Column('views', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forums', 'views')
    # ### end Alembic commands ###
