"""fresh_migration_after_constraint_fix

Revision ID: ac262badf6c6
Revises: d50159c9884d
Create Date: 2025-07-02 13:38:50.609595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac262badf6c6'
down_revision: Union[str, None] = 'd50159c9884d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('station_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'station_id')
    # ### end Alembic commands ###
