"""Stations Migrations  migration

Revision ID: ce64b0acc9c8
Revises: 12e03dda7046
Create Date: 2025-06-07 12:23:21.159601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce64b0acc9c8'
down_revision: Union[str, None] = '12e03dda7046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_fingerprint')
    # ### end Alembic commands ###
