"""Stations Migrations  migration

Revision ID: d3d4e79d2399
Revises: 5caca1d2182b
Create Date: 2025-06-01 02:27:13.747736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d4e79d2399'
down_revision: Union[str, None] = '5caca1d2182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('backup_streaming_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'backup_streaming_link')
    # ### end Alembic commands ###
