"""Systemlogs  Migrations

Revision ID: d50159c9884d
Revises: 406b8bc0bc20
Create Date: 2025-06-22 18:12:34.113713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd50159c9884d'
down_revision: Union[str, None] = '406b8bc0bc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'organizer_phone')
    op.drop_column('events', 'max_attendees')
    op.drop_column('events', 'ticket_price')
    op.drop_column('events', 'facebook_event_url')
    op.drop_column('events', 'registration_required')
    op.drop_column('events', 'video_url')
    op.drop_column('events', 'contact_person')
    op.drop_column('events', 'notes')
    op.drop_column('events', 'timezone')
    op.drop_column('events', 'contact_email')
    op.drop_column('events', 'current_attendees')
    op.drop_column('events', 'recurrence_pattern')
    op.drop_column('events', 'website_url')
    op.drop_column('events', 'audio_url')
    op.drop_column('events', 'is_recurring')
    op.drop_column('events', 'twitter_hashtag')
    op.drop_column('events', 'registration_deadline')
    op.drop_column('events', 'contact_phone')
    op.drop_column('events', 'organizer_name')
    op.drop_column('events', 'custom_fields')
    op.drop_column('events', 'instagram_url')
    op.drop_column('events', 'organizer_email')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'tags')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'gallery_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('gallery_images', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('events', sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True))
    op.add_column('events', sa.Column('tags', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('events', sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('events', sa.Column('organizer_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('instagram_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('events', sa.Column('custom_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('events', sa.Column('organizer_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('contact_phone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('events', sa.Column('registration_deadline', mysql.DATETIME(), nullable=True))
    op.add_column('events', sa.Column('twitter_hashtag', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('events', sa.Column('is_recurring', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('audio_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('events', sa.Column('website_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('events', sa.Column('recurrence_pattern', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('events', sa.Column('current_attendees', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('contact_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('timezone', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('events', sa.Column('notes', mysql.TEXT(), nullable=True))
    op.add_column('events', sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('events', sa.Column('video_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('events', sa.Column('registration_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('facebook_event_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('events', sa.Column('ticket_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('events', sa.Column('max_attendees', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('organizer_phone', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
