"""Slugs Stations Migrations  migration

Revision ID: f61e4aca7f58
Revises: 44973ec12998
Create Date: 2025-06-13 08:19:32.783958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61e4aca7f58'
down_revision: Union[str, None] = '44973ec12998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_programs', sa.Column('listener_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_programs', 'listener_favorite')
    # ### end Alembic commands ###
