"""Stations Migrations  migration

Revision ID: fb69bd46be23
Revises: 0306b0545315
Create Date: 2025-05-31 23:58:42.688058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb69bd46be23'
down_revision: Union[str, None] = '0306b0545315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_programs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('studio', sa.String(length=10), nullable=False),
    sa.Column('hosts', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radio_programs_station_id'), 'radio_programs', ['station_id'], unique=False)
    op.create_index(op.f('ix_radio_programs_title'), 'radio_programs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radio_programs_title'), table_name='radio_programs')
    op.drop_index(op.f('ix_radio_programs_station_id'), table_name='radio_programs')
    op.drop_table('radio_programs')
    # ### end Alembic commands ###
